requests:
 eod : 'https://financialmodelingprep.com/stable/historical-price-eod/light?symbol={symbol}&from={from_date}&to={to_date}&apikey={key}'
 1min : 'https://financialmodelingprep.com/stable/historical-chart/1min?symbol={symbol}&apikey={key}'
 5min : 'https://financialmodelingprep.com/stable/historical-chart/5min?symbol={symbol}&apikey={key}'

tickers:
  apple: AAPL

keys:
  stock_key: 'YX585dbl6mHbJX8gtLzESZ4MdpAdYfhg'