requests:
 eod : 'https://financialmodelingprep.com/stable/historical-chart?symbol={symbol}&from={fromdate}&to={todate}&apikey={key}'
 1min : 'https://financialmodelingprep.com/stable/historical-chart/1min?symbol={symbol}&apikey={key}'
 5min : 'https://financialmodelingprep.com/stable/historical-chart/5min?symbol={symbol}&apikey={key}'

